<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('simstring')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_simstring.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('simstring.so')) return;
    } else {
      if (!dl('simstring.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class Simstring_ {
	const exact = 0;

	const dice = dice;

	const cosine = cosine;

	const jaccard = jaccard;

	const overlap = overlap;
}

/* PHP Proxy Classes */
class Simstring_StringVector {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_simstring_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_simstring_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __construct($n=null) {
		if (is_resource($n) && get_resource_type($n) === '_p_std__vectorT_std__string_t') {
			$this->_cPtr=$n;
			return;
		}
		switch (func_num_args()) {
		case 0: $this->_cPtr=new_StringVector(); break;
		default: $this->_cPtr=new_StringVector($n);
		}
	}

	function size() {
		return StringVector_size($this->_cPtr);
	}

	function capacity() {
		return StringVector_capacity($this->_cPtr);
	}

	function reserve($n) {
		StringVector_reserve($this->_cPtr,$n);
	}

	function clear() {
		StringVector_clear($this->_cPtr);
	}

	function push($x) {
		StringVector_push($this->_cPtr,$x);
	}

	function is_empty() {
		return StringVector_is_empty($this->_cPtr);
	}

	function pop() {
		return StringVector_pop($this->_cPtr);
	}

	function get($i) {
		return StringVector_get($this->_cPtr,$i);
	}

	function set($i,$val) {
		StringVector_set($this->_cPtr,$i,$val);
	}
}

class Simstring_writer {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_simstring_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_simstring_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __construct($filename,$n=3,$be=false,$unicode=false) {
		if (is_resource($filename) && get_resource_type($filename) === '_p_writer') {
			$this->_cPtr=$filename;
			return;
		}
		$this->_cPtr=new_writer($filename,$n,$be,$unicode);
	}

	function insert($string) {
		writer_insert($this->_cPtr,$string);
	}

	function close() {
		writer_close($this->_cPtr);
	}
}

class Simstring_reader {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'measure') return reader_measure_set($this->_cPtr,$value);
		if ($var === 'threshold') return reader_threshold_set($this->_cPtr,$value);
		if ($var === 'thisown') return swig_simstring_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if (function_exists('reader_'.$var.'_set')) return true;
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'measure') return reader_measure_get($this->_cPtr);
		if ($var === 'threshold') return reader_threshold_get($this->_cPtr);
		if ($var === 'thisown') return swig_simstring_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __construct($filename) {
		if (is_resource($filename) && get_resource_type($filename) === '_p_reader') {
			$this->_cPtr=$filename;
			return;
		}
		$this->_cPtr=new_reader($filename);
	}

	function retrieve($query) {
		$r=reader_retrieve($this->_cPtr,$query);
		if (is_resource($r)) {
			$c='Simstring_'.substr(get_resource_type($r), (strpos(get_resource_type($r), '__') ? strpos(get_resource_type($r), '__') + 2 : 3));

			if (class_exists($c)) return new $c($r);
			return new Simstring_StringVector($r);
		}
		return $r;
	}

	function check($query) {
		return reader_check($this->_cPtr,$query);
	}

	function close() {
		reader_close($this->_cPtr);
	}
}


?>
